AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Alarm Gen

  A simple lambda function that creates Cloudwatch alarms for production workload

Globals:
  Function:
    Timeout: 3

Resources:
  AlarmGenFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: alarm_gen/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - arm64
      Events:
        EC2LaunchEvent:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - aws.ec2
              detail-type:
                - AWSAPICallviaCloudTrail
              detail:
                eventSource:
                  - ec2.amazonaws.com
                eventName:
                  - RunInstances
            State: ENABLED